### ISSUE TITLE
[Bug]: No publishable resources

### ISSUE THREAD

**Issue by jamesautodude** [grantholle/laravel-timezone#2]
### What happened?

When trying to publish Migration & Config files, I get:

```
INFO  No publishable resources for tag [laravel-timezone-migrations].

INFO  No publishable resources for tag [laravel-timezone-config].
```

### How to reproduce the bug

Running these commands after composer require:

`php artisan vendor:publish --tag="laravel-timezone-migrations"`

`php artisan vendor:publish --tag="laravel-timezone-config"`

### Package Version

1.0

### PHP Version

8.2

### Laravel Version

10.0

### Which operating systems does with happen with?

Linux

**Comment by grantholle** [comment]
I've updated the readme. The tags should just be `timezone-config` or `timezone-migrations`.
