### ISSUE TITLE
[Bug]: Creating from a standard laravel date fails

### ISSUE THREAD

**Issue by xtfer** [grantholle/laravel-timezone#5]
### What happened?

Attempting to convert a standard Laravel created_at field fails.
 

### How to reproduce the bug

e.g. `2023-05-16 11:44:30` returns `21/05/2023 01:05 pm`, which is the current date and an odd time.

```
$data = CarbonImmutable::make($data);
$date = \GrantHolle\Timezone\Facades\Timezone::toLocal($data, 'd/m/Y h:m a');
```

### Package Version

latest

### PHP Version

8.1

### Laravel Version

10.0

**Comment by grantholle** [comment]
Could you provide a test repo or let me know the original timezone of `$data` and the intended/expected output timezone?

**Comment by xtfer** [comment]
@grantholle The original data and test case is in the bug report.

**Comment by grantholle** [comment]
The time is wrong because you're using the wrong format character. It should be `i` (minutes with leading zeros) instead of `m` (numeric representation of a month, with leading zeros).

Based on your example, here is my results that work as expected:

```
> $data = Carbon\CarbonImmutable::make('2023-05-16 11:44:30');
= Carbon\CarbonImmutable @1684251870 {#8349
    date: 2023-05-16 11:44:30.0 America/New_York (-04:00),
  }

> $date = \GrantHolle\Timezone\Facades\Timezone::toLocal($data, 'd/m/Y h:i a');
= "16/05/2023 03:44 pm"
```

If the output of `toLocal` is "right now", that means the first parameter is null.

```
public function toLocal(null|Carbon|CarbonImmutable $date, string $format = null): string|CarbonImmutable
{
    // If $date is null, it will be now
    $date = $date ?? now();

    // getCurrentTimezone will be either
    // 1. The authenticated user's timezone
    // 2. The value of config('timezone.fallback')
    // 3. The value of config('app.timezone')
    $converted = CarbonImmutable::make($date)
        ->setTimezone($this->getCurrentTimezone());

    // If there's no format value, return the CarbonImmutable instance
    if (!$format) {
        return $converted;
    }

    // If there is a format, go ahead and format it
    return $converted->format($format);
}
```

I've written notes on the logic of how the `toLocal` function works.

**Comment by xtfer** [comment]
You are correct - seems like an obvious mistake now. Thanks for your help.

**Comment by xtfer** [comment]
Well, something is going on... and it seems to relate to your test case. _Every_ date is returning 16-5-2023 at X:44 pm...

![CleanShot 2023-05-23 at 21 06 32](https://github.com/grantholle/laravel-timezone/assets/40190/79e2790d-7e9f-49cf-952b-d94b63b2f629)

**Comment by xtfer** [comment]
Great, thanks for your help.
